version: "3.8"
services:
  library-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sql_server2019_library
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SALibrary2023"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - microservices

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=BorrowLibrary 
      - RABBITMQ_DEFAULT_PASS=BorrowLibraryPassword
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microservices

  library:
    image: library_image
    container_name: library_service_container
    ports:
      - "5011:80"
      - "5001:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: sergey@$
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - microservices
    restart: always

networks:
  microservices:
    external: true
