version: "3.8"
services:
  ms-sql-library-server:
      image: "mcr.microsoft.com/mssql/server:2019-latest"
      container_name: sql_server2019_library
      environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Password2019"
        MSSQL_PID: Express
      ports:
        - "1433:1433"

  library:
    image: libraryimage
    container_name: library_service_container
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5001:80"

  